# Generated by Django 5.2.3 on 2025-06-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('module', models.CharField(choices=[('offer_panel', 'Oferta panel'), ('offer_public', 'Oferta publiczna'), ('register', 'Rejestracja'), ('issues', 'Problemy')], max_length=50)),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='issue_attachments/')),
            ],
        ),
    ]
