# Generated by Django 5.2.3 on 2025-06-17 16:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gdpr_consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Oczekujące'), ('confirmed', 'Potwierdzone'), ('cancelled', 'Anulowane')], default='pending', max_length=50)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Numer telefonu musi być w formacie: '+999999999'. Od 9 do 15 cyfr.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='offer_panel.course')),
            ],
        ),
    ]
